import type { Metadata } from "next";
import Link from "next/link";
import { LessonShell } from "@/components/LessonShell";
import { CodeBlock } from "@/components/CodeBlock";
import { Callout } from "@/components/Callout";
import { LayerCake } from "@/components/LayerCake";
import { LayerSorter } from "@/components/LayerSorter";
import { LessonQuote } from "@/components/LessonQuote";

export const metadata: Metadata = { title: "Data layers" };

export default function Page() {
  return (
    <LessonShell
      section="learn"
      slug="data-layers"
      kicker="Learn 04"
      title="Data layers"
      lede="Each layer gives the next one a different promise: faithful source evidence, a consistently prepared source, reusable transformations, business-ready marts, and governed datasets for named products."
      minutes={24}
    >
      <h2>Why separate the layers?</h2>
      <p>
        Open a source table and almost nothing is safe to assume. A column that
        looks like a date may be text. Two rows may be separate events, duplicate
        submissions, or successive versions of the same event. A provider code
        names an organisation, but perhaps not the organisation that currently
        owns the pathway. Even “person” may mean a source-specific identifier in
        one feed and a project-wide identity in another.
      </p>
      <p>
        An analyst can settle all of that inside one query. The difficulty is
        that the next analyst has to settle it again — and can make a different,
        equally plausible choice. A shared project instead resolves each
        decision once, tests it, and makes the answer available to everything
        above it. The layers help us decide which model should own each kind of
        decision.
      </p>
      <p>
        This is not a conveyor belt where work “starts” at the bottom and
        “finishes” at the top. A developer may begin by querying a reporting
        model, discover that a shared concept is missing, add it in modelling,
        and never create a published output. What matters is the responsibility
        and intended consumers of the model being changed — the sequence of the
        work is free to run in any direction.
      </p>

      <LayerCake />

      <p>
        Read the stack as a translation. At the bottom, data speaks in the
        language of a source system: its files, columns, codes and accidents. As
        it moves upward it speaks more of the organisation&apos;s language:
        pathways, appointments, people, registers and providers. At the top it
        speaks to a particular consumer, under a particular policy.
      </p>
      <LessonQuote
        attribution="dbt Labs, the company behind dbt"
        work="How we structure our dbt projects"
        href="https://docs.getdbt.com/best-practices/how-we-structure/1-guide-overview"
      >
        One foundational principle that applies to all dbt projects though, is
        the need to establish a cohesive arc moving data from source-conformed
        to business-conformed. Source-conformed data is shaped by external
        systems out of our control, while business-conformed data is shaped by
        the needs, concepts, and definitions we create.
      </LessonQuote>

      <h2>Follow one domain up the stack</h2>
      <p>
        We will use the waiting-list feed throughout. The eventual request might
        be “how many people are currently waiting at each provider?”, but the
        project should model the durable domain behind that first output. It
        needs concepts that make adjacent questions answerable: a submitted
        pathway record, a pathway&apos;s state at a snapshot, a provider, a
        person, and elapsed waiting time.
      </p>

      <h3>Raw — preserve the source evidence</h3>
      <p>
        <em>The contract here: a faithful, readable record of what the source supplied.</em>
      </p>
      <p>
        The waiting-list feed arrives in source-owned tables. Raw models expose
        every row and every value without deciding what any of it means. They
        project the physical columns through readable <code>snake_case</code>{" "}
        names, but do not cast, filter, deduplicate or join.
      </p>
      <CodeBlock
        lang="sql"
        title="raw_wl_wl_openpathways_data · simplified"
        code={`
select
    "PSEUDO NHS NUMBER"   as pseudo_nhs_number,
    "WEEK ENDING DATE"    as week_ending_date,
    "REFERRAL TO TREATMENT PERIOD START DATE"
        as referral_to_treatment_period_start_date
from {{ source('wl', 'WL_OpenPathways_Data') }}
`}
      />
      <p>
        These models are generated by scripts —{" "}
        <strong>you never write or edit a raw model by hand</strong>. That rule
        creates a valuable point of comparison. If a row exists in the source,
        it exists here; if it does not, no project logic has invented it. When a
        later number looks suspicious, raw answers the first diagnostic
        question without interpretation: “what evidence did we receive?”
      </p>
      <Callout kind="info" title="The raw promise">
        <p>
          Downstream readers may assume that raw faithfully represents the supplied
          source table and contains no analytical interpretation. Readability has
          changed; evidence has not.
        </p>
      </Callout>

      <h3>Staging — prepare one source for every downstream use</h3>
      <p>
        <em>
          The contract here: one consistently named and typed source object,
          ready to be used by downstream models.
        </em>
      </p>
      <p>
        Source systems rarely arrive ready to join. Identifiers have
        source-specific names, dates have awkward types, and resubmission
        mechanics are encoded in columns that only make sense if you know the
        feed. Staging applies
        the preparation that should be universal for that source: project names,
        useful types, consistent nulls and fixes for known delivery quirks. It
        should normally preserve the source entity and grain.
      </p>
      <CodeBlock
        lang="sql"
        title="the staging responsibility · simplified"
        code={`
select
    -- the project's name and type for this source identifier
    pseudo_nhs_number as sk_patient_id,

    -- the feed describes weekly snapshots; express its date consistently
    case
        when dayofweekiso(week_ending_date) = 7 then week_ending_date
        else dateadd('day', -dayofweek(week_ending_date), week_ending_date)
    end as week_ending_date,

    referral_to_treatment_period_start_date
from {{ ref('raw_wl_wl_openpathways_data') }}

-- only when the feed contract says a later submission replaces the
-- same technical source record for every possible downstream use
qualify der_submission_id = max(der_submission_id)
    over (partition by <complete source record key>)
`}
      />
      <p>
        The submission identifier and week-ending date describe how this feed is
        delivered. Every use of the feed needs the same answer about which
        resubmission supersedes which, and which reporting week a supplied date
        represents, so staging settles those mechanics once.
      </p>
      <p>
        Staging therefore stays close to one source object: normally one staging
        model per source table and one row for each source entity at its source
        grain. Two tests should pass. The change should be <strong>universal</strong>{" "}
        for every reasonable use of the source, and it should not discard a
        legitimate source record or replace the source entity with a new business
        concept. Inferring a person, constructing a spell, deciding whether a
        pathway is currently open and building a clinical register all belong
        downstream.
      </p>
      <p>
        Staging may still enforce a declared source invariant. If the feed
        contract says that an open-pathways table contains only open pathways,
        removing a row that carries an end date is part of making that source
        trustworthy for every reader. Every downstream use should inherit that
        correction, so it passes the universal test. That is different from
        interpreting a general pathway history and deciding which records the
        organisation considers open.
      </p>
      <p>
        Staging should normally have no joins. A join is justified when its sole
        purpose is cleaning, standardisation or enrichment that every consumer
        of the source should inherit. A business population or consumer-specific
        enrichment fails that universal test and belongs downstream.
      </p>

      <p>
        <strong>SLAM shows how far source preparation can go.</strong>{" "}Provider
        contract-monitoring files vary by provider, month and revision, and each
        submission can restate earlier months. The upstream pipeline reconstructs
        their changing layouts in <code>DATA_LAKE.SDL</code>. Provider text is parsed
        and its file and period provenance recorded by models under{" "}
        <code>models/staging/commissioning/slam/</code>. Their current-statement views
        use the suffix <code>_latest</code>, selecting one statement for each provider,
        financial year and month. This is more work than most staging models do, but
        it remains source-conformed: every consumer needs the same interpretation of
        the file layout, supplied values and cumulative submission history. The base
        tables retain that history, so current reporting should use those views.
      </p>

      <Callout kind="info" title="The staging promise">
        <p>
          Downstream readers receive a clean, consistently named and typed
          version of the source, with universal delivery quirks handled once.
          They may not yet assume that a row is a settled business event or that
          a source status has the organisation&apos;s meaning.
        </p>
      </Callout>

      <Callout kind="info" title="Where raw and staging build">
        <p>
          Both layers use the <code>STAGING</code>{" "}database. All raw models build in
          its single <code>DBT_RAW</code>{" "}schema. Staging models use source or domain
          schemas such as <code>CSDS</code>, <code>OLIDS</code>{" "}and{" "}
          <code>REFERENCE</code>. Development uses the matching layout in{" "}
          <code>DEV__STAGING</code>.
        </p>
      </Callout>

      <h3>Modelling — build clear domain components</h3>
      <p>
        <em>
          The contract here: a purposeful transformation that prepares data for
          one or more marts.
        </em>
      </p>
      <p>
        Staging has made the waiting-list feed readable, but it has not said what
        a pathway <em>is</em>. It has not decided whether successive submissions
        describe one continuing pathway, which complete snapshot counts as
        current, which provider relationship matters, or how waiting time is
        measured at a snapshot. Those are claims about the domain, and they
        should remain useful whether the next request is a provider count, a
        long-wait cohort, a patient-level view or a trend over time.
      </p>
      <CodeBlock
        lang="sql"
        title="illustrative intermediate model"
        code={`
with latest_complete_snapshot as (
    select max(week_ending_date) as snapshot_date
    from {{ ref('stg_wl_openpathways_data') }}
)

select
    sk_patient_id,
    patient_pathway_identifier as pathway_id,
    week_ending_date as snapshot_date,
    provider_code,
    treatment_function_code,

    -- one shared definition of elapsed waiting time at this snapshot
    datediff('day',
        referral_to_treatment_period_start_date,
        week_ending_date) as days_waiting_at_snapshot
from {{ ref('stg_wl_openpathways_data') }}
inner join latest_complete_snapshot
    on week_ending_date = snapshot_date
`}
      />
      <p>
        The rows now make claims in the organisation&apos;s vocabulary: this is the
        agreed current snapshot; this record identifies a pathway; this is how
        long it had been waiting then. The input is already universally prepared
        as an open-pathways source. Modelling adds reusable domain interpretation
        rather than rechecking that source contract.
      </p>
      <p>
        What places a model in this layer is its role: a purposeful component,
        built to be consumed by other dbt models rather than offered as the
        supported starting point for analysis. The <code>int_</code>{" "}prefix
        simply records that role. An intermediate model may still perform
        substantial domain logic, change grain and produce rows that could be
        counted — and a coherent piece of complex logic can deserve its own
        model for readability and testing even when only one mart currently
        uses it. The{" "}
        <Link href="/learn/model-design">model-design lesson</Link>{" "}develops this
        idea.
      </p>

      <Callout kind="info" title="The modelling promise">
        <p>
          Downstream models receive a named, tested transformation with a clear
          purpose. It can isolate complexity, protect a grain or own reusable
          domain rules, but it is not expected to be the complete, supported
          analytical interface for that subject.
        </p>
      </Callout>

      <h3>Reporting — build the marts analysts work from</h3>
      <p>
        <em>
          The contract here: a supported business entity or concept that people
          can analyse directly at a documented grain.
        </em>
      </p>
      <p>
        This is the project&apos;s equivalent of what dbt calls the{" "}
        <a href="https://docs.getdbt.com/best-practices/how-we-structure/4-marts">
          marts layer
        </a>. dbt also calls it an <em>entity layer</em>{" "}or{" "}
        <em>concept layer</em>: each mart represents a business-defined thing at
        its unique grain. A mart might be centred on a person, pathway,
        provider, appointment or clinical register. The first question is not
        “which chart needs this?” but “what does one row represent?”
      </p>
      <p>
        A domain can support several useful marts. From the pathway snapshots,
        the project can select the latest snapshot and build{" "}
        <code>fct_person_wl_current_count_total</code>{" "}— one row per person:
        how many open pathways does this person have? — and{" "}
        <code>fct_provider_wl_current_count_total</code>{" "}— one row per
        provider: how many open pathway rows are recorded here? It can also
        retain one row per pathway for analysts who need the detail. These are
        not three versions of the same table. They are three marts with different core
        concepts and grains, built from the same shared domain meaning.
      </p>
      <p>
        A mart should normally contain the useful context analysts need about
        its core concept. A person mart could include current practice, geography
        and recent activity; a provider mart could include organisation names and
        pathway measures. This deliberate width is denormalisation: the joins
        are performed once in the project instead of being reconstructed in
        every worksheet. The mart may borrow attributes and summaries from many
        concepts while preserving one unmistakable core grain.
      </p>
      <p>
        The reporting mart may also complete the definition of its core concept.
        The diabetes register, for example, is itself a business-ready clinical
        fact. Modelling is not the only place where meaning is allowed. Its job
        is to give supporting transformations clear responsibilities, isolate
        logic that is complex or independently changeable, and make reusable
        steps available to more than one mart. That separation of concerns keeps
        the mart SQL readable without pretending the mart contains no business
        rules of its own.
      </p>
      <p>
        This layer holds dimensions (<code>dim_</code>), facts
        (<code>fct_</code>), point-in-time models (<code>pit_</code>), wide
        analytical tables (<code>obt_</code>) and data-quality outputs
        (<code>dq_</code>). A wide model such as{" "}
        <code>dim_person_demographics</code>{" "}may compose gender, ethnicity,
        geography and practice into one useful person row without privately
        redefining those concepts. The{" "}
        <Link href="/learn/model-naming">model taxonomy lesson</Link>{" "}explains
        how those families turn the project into a searchable map.
      </p>

      <Callout kind="tip" title="A mart is reusable; a product dataset is specific">
        <p>
          A reporting mart is a supported interface for broad analysis of a business
          entity or concept. Analysts may query it directly, but dashboards, extracts
          and operational products should normally be served by published models that
          apply their final shape and controls. Several products can build from the
          same mart without redefining its grain or shared meaning.
        </p>
      </Callout>

      <Callout kind="info" title="The reporting promise">
        <p>
          Readers receive a business-ready mart whose core entity or concept and
          grain are explicit and tested. Commonly needed context is already
          present, and shared definitions have not been reinvented merely for
          one consumer.
        </p>
      </Callout>

      <h3>Published — serve named data products</h3>
      <p>
        <em>
          The contract here: a governed dataset for a named report, dashboard,
          extract or application.
        </em>
      </p>
      <p>
        Reporting marts are reusable analytical assets. When a table or view is
        created to power the monthly waiting-times dashboard, a statutory
        return, an application or a named extract, it becomes a published data
        product. It can select the product&apos;s columns, labels, refresh contract
        and population from the marts below while leaving those reusable marts
        available for other questions.
      </p>
      <p>
        A published model does not need a special legal filter to belong here.
        Its defining feature is that a named consumer depends on it. The layer
        makes that dependency visible, gives the product a stable interface and
        gives the team a clear place to manage ownership, grants and Snowflake
        tags.
      </p>
      <p>
        Some products also carry use-specific policy. Published models are split
        by legal basis — <code>direct_care/</code>{" "}and{" "}
        <code>secondary_use/</code>{" "}— and secondary-use models built on
        GP-record data apply the national opt-out via an inner join to{" "}
        <code>dim_person_secondary_use_allowed</code>. That filter belongs here
        because it governs this use of that data — commissioning datasets do
        not need it — and not because the opted-out person or pathway
        disappears from the shared domain.
      </p>
      <p>
        Not every population rule belongs here. “Open pathway” is shared domain
        meaning and belongs upstream. A reusable clinical cohort may also be a
        shared fact. Published is for the part that becomes true only because of
        the consumer: legal basis, disclosure control, contractual scope,
        product ownership or audience-specific naming.
      </p>

      <Callout kind="info" title="The published promise">
        <p>
          A named product can rely on this table or view as its governed data
          contract. Upstream users can rely on product-specific selections and
          policies not silently rewriting the reusable marts or shared domain.
        </p>
      </Callout>

      <Callout kind="info" title="There is a sixth layer">
        <p>
          <code>models/semantic/</code>{" "}holds Snowflake Semantic Views (
          <code>sem_</code>) — pre-defined facts, dimensions and metrics that give
          downstream query tools an agreed definition of the data. The{" "}
          <Link href="/advanced/semantic-views">semantic views lesson</Link>{" "}
          covers them; they follow the same ref() rules.
        </p>
      </Callout>

      <Callout kind="info" title="Supporting model areas">
        <p>
          <code>models/reference/</code>{" "}holds project-owned lookups and derived
          reference data shared across domains. <code>models/partner/</code>{" "}
          holds governed partner datasets and access mappings. They follow the
          same raw-through-staging boundary but are scopes of ownership rather
          than extra steps in a rigid ladder.
        </p>
      </Callout>

      <h2>The SQL operation does not choose the layer</h2>
      <p>
        The same SQL operation can settle completely different kinds of
        ambiguity — which is why rules of thumb like “joins go in modelling”
        or “filters go in published” break down almost immediately. A single
        join might attach a source lookup, establish a shared clinical
        relationship, assemble a convenient person row or apply a secondary-use
        permission rule: four responsibilities, four different homes.
      </p>
      <p>
        Ask what becomes true after the transformation — and for whom it should
        be true:
      </p>
      <table>
        <thead>
          <tr>
            <th>Transformation</th>
            <th>What it means</th>
            <th>Likely layer</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Keep the latest technical resubmission</td>
            <td>This is the source record every reader should see</td>
            <td>Staging</td>
          </tr>
          <tr>
            <td>Select the latest complete waiting-list snapshot</td>
            <td>This is the shared current state used across analyses</td>
            <td>Modelling</td>
          </tr>
          <tr>
            <td>Summarise open pathways to one row per provider</td>
            <td>This is a provider-grain mart for broad analysis</td>
            <td>Reporting</td>
          </tr>
          <tr>
            <td>Shape the provider mart for the monthly waiting-times dashboard</td>
            <td>This is the stable dataset for a named data product</td>
            <td>Published</td>
          </tr>
        </tbody>
      </table>
      <p>
        All four transformations might use a <code>where</code>,{" "}
        <code>qualify</code>{" "}or join. Their placement differs because they
        have different responsibilities and intended consumers: source-wide
        preparation, reusable modelling, direct analysis or one named product.
      </p>

      <h2>Meaning should become more specific, not more contradictory</h2>
      <p>
        Moving upward may enrich or narrow meaning, but it should not casually
        overturn a promise already made below. Reporting may present an open
        pathway at person or provider grain; it should not quietly use different
        status codes for “open.” A published output may exclude opted-out people;
        it should not alter how their waiting time was calculated.
      </p>
      <CodeBlock
        lang="text"
        title="each boundary lets the next reader assume more"
        code={[
          "source evidence",
          "    → universally cleaned and standardised source records",
          "        → shared domain events, states and relationships",
          "            → business-ready marts at explicit grains",
          "                → governed products for named uses",
        ].join("\n")}
      />
      <p>
        This is why lineage is useful in both directions. Read upward and ask,
        “what new claim is being made here?” Read downward and ask, “which
        assumptions is this model entitled to inherit?” A surprising answer in
        either direction often reveals a misplaced definition.
      </p>

      <Callout kind="smell" title="A dashboard question reaches too far down">
        <p>
          A published waiting-list model reads the raw feed, chooses the latest
          submission, interprets statuses, calculates elapsed time and applies
          opt-out filtering in one file. The final number may be correct, but
          source preparation, domain meaning and audience policy are trapped
          inside one product. The next product must rediscover all three.
        </p>
      </Callout>

      <h2>The same journey, in folders and databases</h2>
      <p>
        Folders make these promises visible and allow project configuration to
        enforce them. They are the physical expression of the conceptual
        boundaries, not the reason those boundaries exist:
      </p>
      <CodeBlock
        lang="text"
        title="models/ · one folder per scope of meaning"
        code={`
models/
├── raw/          source evidence preserved; generated, never hand-edited
├── staging/      universal cleaning and standardisation applied per source
├── reference/    project-owned lookups and derived shared reference data
├── modelling/    purposeful transformations that prepare data for marts
├── reporting/    supported, business-ready marts at explicit grains
├── published/    named data products served and governed
├── partner/      governed partner datasets and access mappings
└── semantic/     agreed metrics exposed to downstream query tools
`}
      />
      <Callout kind="tip" title="Folders do real work">
        <p>
          In the OLIDS domain the Snowflake schema is derived from the folder path:{" "}
          <code>models/modelling/olids/diagnoses/</code>{" "}builds into{" "}
          <code>MODELLING.OLIDS_DIAGNOSES</code>. Create a folder and the schema follows —
          no config needed.
        </p>
      </Callout>
      <p>
        Snowflake mirrors the same journey at database level. Source data lands
        in the data-lake databases; each layer above builds into a database
        named after it:
      </p>
      <CodeBlock
        lang="text"
        title="the layers, as Snowflake databases"
        code={`
DATA_LAKE / DATA_LAKE__NCL          source data lands here (shared)
STAGING                             raw (DBT_RAW schema) and staging models
REFERENCE                           shared project-owned reference models
MODELLING                           int_ building blocks
REPORTING                           dim_ / fct_ / obt_ marts
PUBLISHED_REPORTING__DIRECT_CARE    published products,
PUBLISHED_REPORTING__SECONDARY_USE    split by legal basis
PUBLISHED_REPORTING__PARTNER        governed partner datasets
`}
      />
      <p>
        Development mirrors each of these with a <code>DEV__</code>{" "}prefix —{" "}
        <code>DEV__STAGING</code>, <code>DEV__MODELLING</code>{" "}and so on —
        with one exception: the data lake has no mirror. Development reads real
        source data in place and writes only to the <code>DEV__</code>{" "}
        databases. A useful consequence: the database in a query&apos;s FROM
        clause always tells you which layer, and which environment, you are
        reading.
      </p>

      <h2>When a boundary is genuinely difficult</h2>
      <p>
        Some choices really are close. “Current” could mean the latest snapshot
        received, the latest complete snapshot across all providers, or the
        state on an explicitly supplied reporting date. The right answer cannot
        be inferred from the word or from a prefix. Work through the concept:
      </p>
      <ol>
        <li>
          <strong>Name the ambiguity.</strong>{" "}Is this about reading the feed,
          defining the domain, choosing an analytical grain or serving a use?
        </li>
        <li>
          <strong>Name the scope.</strong>{" "}Should every source reader, every
          organisational analysis or only this product inherit the decision?
        </li>
        <li>
          <strong>Name the grain and time.</strong>{" "}What does one row represent,
          and as of when is the claim true?
        </li>
        <li>
          <strong>Name the counterfactual.</strong>{" "}If the dashboard,
          geography or audience changed, should this definition remain?
        </li>
        <li>
          <strong>Name the promise.</strong>{" "}What may downstream readers safely
          stop thinking about after this model?
        </li>
      </ol>
      <p>
        If the answers pull in different directions, the transformation may be
        doing two jobs and deserve two models. The point of the layers is not to
        eliminate judgement. It is to give the judgement a shared vocabulary
        and make its consequences visible.
      </p>

      <h2>Why the separation pays</h2>
      <p>
        Every well-kept boundary removes a class of questions. Raw preserves an
        audit trail. Staging prevents source quirks being reinterpreted in every
        model. Modelling isolates reusable transformations and gives them more
        surface area for testing. Reporting provides coherent marts and spares
        analysts repeated joins. Published gives named data products stable,
        governed interfaces without contaminating shared models.
      </p>
      <p>
        That is a stronger benefit than knowing which folder accepts a join.
        The stack turns trust into something structural: a reader can tell what
        kind of decisions a model is allowed to contain, what it inherits, and
        what it promises to everything downstream.
      </p>

      <h2>Try reading the decision, not the syntax</h2>
      <p>
        For each description, ignore whether it happens to use a cast, join,
        filter or aggregation. Ask which ambiguity it settles and who should
        inherit the answer.
      </p>
      <LayerSorter />
    </LessonShell>
  );
}
